package com.aurora.music.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class YouTubeDownloadsTest {
    private val options = listOf(
        YouTubeAudioOption("opus-50", YouTubeDownloadFormat.OPUS, 51),
        YouTubeAudioOption("opus-70", YouTubeDownloadFormat.OPUS, 68),
        YouTubeAudioOption("opus-160", YouTubeDownloadFormat.OPUS, 134),
        YouTubeAudioOption("aac-48", YouTubeDownloadFormat.M4A, 49),
        YouTubeAudioOption("aac-128", YouTubeDownloadFormat.M4A, 130),
    )

    @Test fun picksTheBestStreamOfThePreferredFormat() {
        assertEquals("opus-160", YouTubeDownloads.pick(options, YouTubeDownloadPrefs())?.url)
        assertEquals("aac-128", YouTubeDownloads.pick(options, YouTubeDownloadPrefs(YouTubeDownloadFormat.M4A))?.url)
    }

    @Test fun bitrateLimitChoosesTheClosestTierAtOrBelowIt() {
        assertEquals("aac-128", YouTubeDownloads.pick(options, YouTubeDownloadPrefs(YouTubeDownloadFormat.M4A, 128))?.url)
        assertEquals("opus-70", YouTubeDownloads.pick(options, YouTubeDownloadPrefs(maxBitrateKbps = 64))?.url)
        assertEquals("aac-48", YouTubeDownloads.pick(options, YouTubeDownloadPrefs(YouTubeDownloadFormat.M4A, 64))?.url)
    }

    @Test fun fallsBackWhenThePreferenceIsUnavailable() {
        val aacOnly = options.filter { it.format == YouTubeDownloadFormat.M4A }
        assertEquals("aac-128", YouTubeDownloads.pick(aacOnly, YouTubeDownloadPrefs())?.url)
        assertEquals("aac-128", YouTubeDownloads.pick(options, YouTubeDownloadPrefs(), setOf(YouTubeDownloadFormat.M4A))?.url)
        val high = listOf(YouTubeAudioOption("opus-160", YouTubeDownloadFormat.OPUS, 134))
        assertEquals("opus-160", YouTubeDownloads.pick(high, YouTubeDownloadPrefs(maxBitrateKbps = 64))?.url)
        assertNull(YouTubeDownloads.pick(emptyList(), YouTubeDownloadPrefs()))
        assertNull(YouTubeDownloads.pick(listOf(YouTubeAudioOption("", YouTubeDownloadFormat.OPUS, 134)), YouTubeDownloadPrefs()))
    }

    @Test fun readsAlbumAndYearFromLabelDescriptions() {
        val description = "Provided to YouTube by Example Records\n\nNight Drive · Neon Lanterns · Marlow Vance\n\nAfterglow\n\n℗ 2021 Example\n\nReleased on: 2021-03-05\n\nAuto-generated by YouTube."
        assertEquals(YouTubeTrackTags("Night Drive", "Neon Lanterns, Marlow Vance", "Afterglow", "2021"),
            YouTubeDownloads.tags("Night Drive", "Neon Lanterns - Topic", description, 2023))
    }

    @Test fun ordinaryVideosKeepTheirTitleAndUploader() {
        assertEquals(YouTubeTrackTags("Live Session", "Some Channel", "", "2019"),
            YouTubeDownloads.tags(" Live Session ", "Some Channel", "A normal description\nwith lines", 2019))
        assertEquals(YouTubeTrackTags("Song", "Artist"), YouTubeDownloads.tags("Song", "Artist - Topic", "", null))
    }

    @Test fun fileNamesAreSafeForSharedStorage() {
        assertEquals("AC DC - Back In Black.opus",
            YouTubeDownloads.fileName(YouTubeTrackTags("Back: In? Black", "AC/DC"), YouTubeDownloadFormat.OPUS))
        assertEquals("Title.m4a", YouTubeDownloads.fileName(YouTubeTrackTags("Title", ""), YouTubeDownloadFormat.M4A))
        assertEquals("YouTube audio.m4a", YouTubeDownloads.fileName(YouTubeTrackTags("???", ""), YouTubeDownloadFormat.M4A))
        assertEquals(124, YouTubeDownloads.fileName(YouTubeTrackTags("x".repeat(300), ""), YouTubeDownloadFormat.M4A).length)
    }
}
